---
title: "Homework 2: Grading System"
author: "Louis Sirugue"
date: "`r format(Sys.time(), '%m/%Y')`"
output: 
  html_document:
    theme: cosmo
    css: ../source/style.css
    includes:
      in_header: ../source/header.html
---

<br>

```{r setup, include = F}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
lapply(c("tidyverse", "kableExtra"), library, character.only = T)
```

```{r table_notes}
kable(tibble(question = c(paste("Question", 1:6), paste("Question", 1:3), "Question 1",
                          "Code chunk annotation and use of inline code", "Redaction quality and overall presentation"),
             grade = c(paste0("/", c(2, 2, 2, 2, 2, 2)), paste0("/", c(2, 2, 2)), "/4", rep("/1", 2))),
      col.names = NULL,
      align = c("lc")) %>%
  kable_styling(bootstrap_options = c("condensed"), full_width = F) %>%
  column_spec(1, width_min = "20em") %>%
  pack_rows("Part I: Quantifying labor market discrimination (12 points)", 1, 6) %>%
  pack_rows("Part II: Neighborhood characteristics (6 points)", 7, 9) %>%
  pack_rows("Part III: Data visualization (4 points)", 10, 10) %>%
  pack_rows("Presentation of the document (2 points)", 11, 12)
```

<br><br>
